# Generated by Django 3.2 on 2023-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('MODER', 'moderator'), ('ADMIN', 'admin')], default='USER', max_length=20, verbose_name='Роль'),
        ),
    ]
