# Generated by Django 3.2 on 2023-10-01 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_emailverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='confirm_code',
        ),
    ]
